[INFO]2022-07-03 12:07:35,280: #################################################################
[INFO]2022-07-03 12:07:35,280: Perform log
[INFO]2022-07-03 12:07:35,280: #################################################################
[INFO]2022-07-03 12:07:35,281: name:56:Use case writer:zpou
[INFO]2022-07-03 12:07:35,283: Enter function : flow_weather()
[INFO]2022-07-03 12:07:35,283: Input parameter : update_dict, value : value is empty.
[INFO]2022-07-03 12:07:35,284: Enter function : flow_login()
[INFO]2022-07-03 12:07:35,285: Input parameter : update_dict, value : value is empty.
[INFO]2022-07-03 12:07:35,286: apileft:57:interface message: {'url': '/api/mgr/signin', 'type': 'post', 'api_type': 'http', 'location_interface': 'my_api_login', 'request': {'username': 'byhy', 'password': '88888888'}, 'reponses_type': 'json', 'Content-Type': 'data', 'cyclical_pattern': {'flag': False, 'judgement_condition': {'right_or_wrong': {'ret': 0}}}}
[INFO]2022-07-03 12:07:35,288: apileft:66:requests url: http://127.0.0.1:80/api/mgr/signin
[INFO]2022-07-03 12:07:35,289: apileft:70:request method: post
[INFO]2022-07-03 12:07:35,290: apileft:75:requests parameter: {'username': 'byhy', 'password': '88888888'}
[INFO]2022-07-03 12:07:35,291: apileft:81:headers: {'content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 'x-requested-with': 'XMLHttpRequest', 'sec-ch-ua-platform': 'Windows', 'Sec-Fetch-Site': 'same-origin', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Dest': 'empty', 'Cookie': 'csrftoken = ftE3dWoJqtQx963qTSGEtPPD62a3dntwBQWBacLeot1E1ntBWX7DE75O6EhU53kg'}
[DEBUG]2022-07-03 12:07:35,295: Starting new HTTP connection (1): 127.0.0.1:80
[DEBUG]2022-07-03 12:07:35,964: http://127.0.0.1:80 "POST /api/mgr/signin HTTP/1.1" 200 10
[INFO]2022-07-03 12:07:35,966: respones:107:In response to the results: {'ret': 0}
[ERROR]2022-07-03 12:07:35,967: flow_login:31:Login failed
[ERROR]2022-07-03 12:07:35,969: flow_login:32:Traceback (most recent call last):
  File "D:\my_api\confdb\flow\user\user.py", line 28, in flow_login
    raise Exception('Login failed')
Exception: Login failed

[INFO]2022-07-03 12:07:35,970: flow_weather:29:TypeError: update_dict is not dict!
[INFO]2022-07-03 12:07:35,971: apileft:57:interface message: {'url': '/api/mgr/customers', 'type': 'post', 'location_interface': 'my_api', 'api_type': 'http', 'request': {'action': 'add_customer', 'data': {'name': 'ds', 'phonenumber': '17674573105', 'address': 'dasasdasd'}}, 'reponses_type': 'json', 'Content-Type': 'json', 'cyclical_pattern': {'flag': False, 'judgement_condition': {'right_or_wrong': {'ret': 0}}}}
[INFO]2022-07-03 12:07:35,973: apileft:66:requests url: http://127.0.0.1:80/api/mgr/customers
[INFO]2022-07-03 12:07:35,974: apileft:70:request method: post
[INFO]2022-07-03 12:07:35,975: apileft:75:requests parameter: {}
[INFO]2022-07-03 12:07:35,976: apileft:81:headers: None
[DEBUG]2022-07-03 12:07:36,046: http://127.0.0.1:80 "POST /api/mgr/customers HTTP/1.1" 200 21
[INFO]2022-07-03 12:07:36,048: respones:107:In response to the results: {'ret': 0, 'id': 126}
[ERROR]2022-07-03 12:07:36,049: flow_weather:37:Failed to create a user!
[ERROR]2022-07-03 12:07:36,051: flow_weather:38:Traceback (most recent call last):
  File "D:\my_api\confdb\flow\user\client.py", line 32, in flow_weather
    raise Exception('Failed to create a user!')
Exception: Failed to create a user!

